/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "euaegjptuiwnaymxvavx"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1YWVnanB0dWl3bmF5bXh2YXZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3MDkwNzEsImV4cCI6MjA3OTI4NTA3MX0.GVG_SsMFjKXq0wh_FGy3aczwu8h-pdwczOwXd-Lz4iE"
